#!/bin/bash
# ==============================================================================
# FUPLA-droneSIM: PX4 SITL Instance Launcher
# ==============================================================================
# Description:
#   Launches a single PX4 SITL instance with the correct environment variables.
#   Instance 1 acts as the Gazebo server (master).
#   Instances 2+ run in standalone mode, attaching to the existing Gazebo server.
#
# Usage:
#   run_px4_instance.sh <drone_id> <model> [pose]
#
# Arguments:
#   drone_id : Integer (1 = master/GZ server, 2+ = client/standalone)
#   model    : PX4 Gazebo model name (gz_x500, gz_x500_depth)
#   pose     : Spawn pose as "x,y,z,roll,pitch,yaw" (optional, default: "0,0,0.2,0,0,0")
#
# Examples:
#   run_px4_instance.sh 1 gz_x500
#   run_px4_instance.sh 2 gz_x500_depth "2,0,0.2,0,0,0"
#
# ==============================================================================

set -e

# --- Argument Validation ------------------------------------------------------

if [ "$#" -lt 2 ]; then
    echo "[ERROR] Usage: $0 <drone_id> <model> [pose]"
    echo "[ERROR] Example: $0 1 gz_x500"
    exit 1
fi

DRONE_ID="$1"
MODEL="$2"
POSE="${3:-0,0,0.2,0,0,0}"  # Default spawn position if not provided

# --- Path Resolution ----------------------------------------------------------
# Resolve the absolute path to the repository root (two levels up from tools/)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
REPO_ROOT="$( cd "$SCRIPT_DIR/.." >/dev/null 2>&1 && pwd )"
PX4_PATH="$REPO_ROOT/external/PX4-Autopilot"
PX4_BIN="$PX4_PATH/build/px4_sitl_default/bin/px4"

# gz_env.sh is generated by PX4 build system and sets:
#   PX4_GZ_MODELS    - path to Gazebo model files
#   PX4_GZ_WORLDS    - path to Gazebo world files
#   GZ_SIM_RESOURCE_PATH - Gazebo resource search path (models + worlds)
# Without these, Gazebo cannot find PX4 drone models and plugins,
# resulting in "Service call timed out" error.
GZ_ENV_SCRIPT="$PX4_PATH/build/px4_sitl_default/rootfs/gz_env.sh"

# --- Pre-flight Checks --------------------------------------------------------

if [ ! -d "$PX4_PATH" ]; then
    echo "[ERROR] PX4-Autopilot not found at: $PX4_PATH"
    echo "[ERROR] Did you run 'git submodule update --init --recursive'?"
    exit 1
fi

if [ ! -f "$PX4_BIN" ]; then
    echo "[ERROR] PX4 binary not found at: $PX4_BIN"
    echo "[ERROR] Did you run 'tools/install.sh'?"
    exit 1
fi

if [ ! -f "$GZ_ENV_SCRIPT" ]; then
    echo "[ERROR] Gazebo environment script not found at: $GZ_ENV_SCRIPT"
    echo "[ERROR] Did you run 'tools/install.sh'? (PX4 must be built first)"
    exit 1
fi

# --- Gazebo Environment Setup -------------------------------------------------
# Source the PX4-generated Gazebo environment script.
# This sets GZ_SIM_RESOURCE_PATH so Gazebo can find drone models and worlds.
# Note: gz_env.sh uses absolute paths generated at PX4 build time.
#       If the repo is moved, PX4 must be rebuilt (DONT_RUN=1 make px4_sitl gz_x500).
echo "[INFO] Sourcing Gazebo environment: $GZ_ENV_SCRIPT"
# shellcheck source=/dev/null
source "$GZ_ENV_SCRIPT"

# Verify that the environment was set correctly
if [ -z "$GZ_SIM_RESOURCE_PATH" ]; then
    echo "[ERROR] GZ_SIM_RESOURCE_PATH is empty after sourcing gz_env.sh"
    echo "[ERROR] Try rebuilding PX4: cd external/PX4-Autopilot && DONT_RUN=1 make px4_sitl gz_x500"
    exit 1
fi

echo "[INFO] GZ_SIM_RESOURCE_PATH=$GZ_SIM_RESOURCE_PATH"

# --- Autostart ID Mapping -----------------------------------------------------
# PX4 SYS_AUTOSTART codes define the vehicle type and default parameters.
# 4001 = Generic Quadrotor (x500)
# 4002 = Generic Quadrotor with Depth Camera (x500_depth)

case "$MODEL" in
    gz_x500)
        AUTOSTART=4001
        ;;
    gz_x500_depth)
        AUTOSTART=4002
        ;;
    *)
        echo "[ERROR] Unknown model: '$MODEL'"
        echo "[ERROR] Supported models: gz_x500, gz_x500_depth"
        exit 1
        ;;
esac

# --- Instance Configuration ---------------------------------------------------
# PX4 uses the instance ID (-i flag) to offset network ports:
#   MAVLink UDP: 14540 + (id - 1)  →  id=1: 14540, id=2: 14541, ...
#   Gazebo:      Instance 1 starts the server; others attach via PX4_GZ_STANDALONE=1

echo "============================================================"
echo " FUPLA-droneSIM: Starting PX4 SITL Instance"
echo "============================================================"
echo "  Drone ID  : $DRONE_ID"
echo "  Model     : $MODEL"
echo "  Autostart : $AUTOSTART"
echo "  Pose      : $POSE"
echo "  PX4 Path  : $PX4_PATH"
echo "============================================================"

# Build the environment variable string based on instance role
if [ "$DRONE_ID" -eq 1 ]; then
    # --- MASTER DRONE (Instance 1) ---
    # This instance is responsible for starting the Gazebo simulation server.
    echo "[INFO] Role: MASTER (Gazebo Server)"
    export PX4_SYS_AUTOSTART="$AUTOSTART"
    export PX4_SIM_MODEL="$MODEL"
    export PX4_GZ_MODEL_POSE="$POSE"
else
    # --- CLIENT DRONE (Instance 2+) ---
    # PX4_GZ_STANDALONE=1 tells PX4 NOT to start a new Gazebo server,
    # but to connect to the already running one from Instance 1.
    echo "[INFO] Role: CLIENT (Attaching to existing Gazebo server)"
    export PX4_SYS_AUTOSTART="$AUTOSTART"
    export PX4_SIM_MODEL="$MODEL"
    export PX4_GZ_MODEL_POSE="$POSE"
    export PX4_GZ_STANDALONE=1
fi

#--- Wait for Gazebo
#px4 gz_bridge uses gazebo service calls to spawn the drone model
#if gazebo is not fully initialized when px4 connects, the service call
#times out and px4 crashes with 'task start failed (-1)'.
#pool the gazebo world service until it responds before starting px4

_wait_for_gazebo() {
    local timeout = 60
    local interval = 2
    local elapsed = 0
    echo "[info] waiting for gazebo to become ready..."

    while [ $elapsed -lt $timeout ]; do
        #gz service -s returns 0 if gazebo is accepting connections
        if gz service -s /gazebo/resource_paths/get \
                --reqtype gz.msgs.Empty \
                --reptype gz.msgs.StringMsg_V \
                --timeout 1000 \
                --req '' > /dev/null 2>&1; then
            echo "[INFO] Gazebo is ready! (waited ${elapsed}s)"
            return 0
        fi

        echo "[info] Gazebo not ready yet... (${elapsed}s / ${timeout}s)"
        sleep $interval
        elapsed=$((elapsed + interval))
    done

    echo "[ERROR] Gazebo did not become ready within ${timeout}s"
    return 1
}


# --- Launch PX4 ---------------------------------------------------------------
# Must cd into PX4_PATH because PX4 uses relative paths internally
cd "$PX4_PATH"

if [ "$DRONE_ID" -eq 1 ]; then
    #master instance: PX4 starts Gazebo server itself.
    #PX4 will start Gazebo and then connect to it.
    echo "[INFO] Role: MASTER - PX4 will start Gazebo server"
    exec "$PX4_BIN" -i "$DRONE_ID"
else
    #client instances: must wait for Gazebo server (started by drone 1)
    #to be fully ready before attempting to connect via gz_bridge.
    _wait_for_gazebo || exit 1
    exec "$PX4_BIN" -i "$DRONE_ID"
fi